### PR TITLE
Fixed the tutorials

### PR DESCRIPTION
**Pull request by VarLad**
When merged,the iframe would become consistent for the tutorials
A demo can be seen here https://varlad.github.io/tutorials/

### CODE REVIEW

**Comment by VarLad** [comment]
@Roger-luo I guess this completes the currently asked task
There are many improvements to be made later though (Check out https://github.com/QuantumBFS/Yao.jl/discussions/282#discussioncomment-806690)
I'll work on them one by one.
For now, this task is complete

**Comment by Roger-luo** [comment]
> For now, this task is complete

IMO, this doesn't complete https://github.com/QuantumBFS/Yao.jl/issues/278 but only adds the iframe resizer, we are far from finishing that issue with this.

you will also need to fix the Documenter issue I mentioned to close that issue.

**Comment by Roger-luo** [comment]
Also I think this implementation is not right, we should use the npm package instead of pushing the entire iframe resizer code into the repo, on the other hand, the best approach is to use the CDN.

**Comment by VarLad** [comment]
@Roger-luo When the CI has completed, if its good to go, kindly merge the PR

I'll be continuing with the Documenter problem

**Comment by VarLad** [comment]
@Roger-luo When the CI has completed, if its good to go, kindly merge the PR

I'll be continuing with the Documenter problem

**Pull request merged**
