### PR TITLE
Made the tutorials more consistent

### PR DESCRIPTION
**Pull request by VarLad**
1. New look to sidebar. Sidebar is also now sticky.
2. Uses PlutoSliderServer instead of PlutoBinder.
3. Implemented a toggler in sidebar.
4. Improved the display on small devices.
5. Implemented a back to top button
6. Fixed the resizing issue

### CODE REVIEW

**Comment by VarLad** [comment]
Demo: https://varlad.github.io/tutorials/getting-started/6-quantum_arithmetic/

**Comment by Roger-luo** [comment]
wow this is nice! just one comment on this

image

can we move the sidebar toggler inside sidebar when it's toggled? or maybe move it to right bottom and add a jump to top button along with it

**Comment by VarLad** [comment]
@Roger-luo Take a look at the site again: https://varlad.github.io/tutorials/getting-started/6-quantum_arithmetic/
Merge if its good to go!

**Comment by Roger-luo** [comment]
image

so I actually meant by right bottom, e.g my blog at blog.rogerluo.dev has this

image

**Comment by Roger-luo** [comment]
current the button will move into the footer when one keep scrolling down

**Comment by VarLad** [comment]
@Roger-luo Done! Ready to merge (?)

**Comment by VarLad** [comment]
Demo: varlad.github.io/tutorials/getting-started/6-quantum_arithmetic

**Comment by VarLad** [comment]
@Roger-luo Proposition: Making the header persistent throughout the tutorials

**Comment by VarLad** [comment]
@Roger-luo Any problems with this one?

**Comment by Roger-luo** [comment]
only one small thing the buttons seems quite hard to press on a phone, I think their position should be a bit more left and top (you can't see it anymore if the chrome bottom banner is toggle)

image

**Comment by VarLad** [comment]
Looks good now？

**Comment by VarLad** [comment]
This one's ready to merge too!

**Comment by Roger-luo** [comment]
@VarLad is there a preview somewhere?

edit: the demo link above doesn't seem to get the update of the PR.

**Comment by VarLad** [comment]
https://varlad.github.io/tutorials/getting-started/6-quantum_arithmetic/

Works for me.... Uhhh... use a different browser? (Cache problems on your side maybe)

**Comment by VarLad** [comment]
(Don't forget to scroll down :sweat_smile: )

**Comment by Roger-luo** [comment]
it seems the button is still on the right boader I think we should have a small margin on the right hand to prevent potential conflict of other UIs making it easier to click/press.

image

**Comment by VarLad** [comment]
That button has a high z-index, so its given more priority under such circumstances
Also, I've reduced the opacity, so the button is kinda "half transparent", so it won't hide other content either

**Comment by Roger-luo** [comment]
my main concern is it is attached to right boader, I think having a small margin on the right looks better, e.g this is the button on my blog site

image

**Comment by Roger-luo** [comment]
imagine you are looking at this page through a touchable device (e.g a phone or an iPad) if the button is attached to the edge, it will be hard to use hand to press it, since the screen may think you are just touching the edge by accident. but if you move it a bit inner, it will be a much clear message that you actually want to press that button.

**Comment by VarLad** [comment]
Oh sorry!!!
OK!! I now know what you meant! 
Sorry for the misunderstanding :man_facepalming:

**Comment by VarLad** [comment]
Pushed it!
Would take 20mins to build!
Here's the preview anyway! (This much is good enough?)

Screenshot from 2021-06-08 20-04-24

**Comment by Roger-luo** [comment]
OK now the layout looks good in general, can we move the style definitions to CSS files? this would make the website easier to organize.

**Comment by Roger-luo** [comment]
great job!

**Pull request merged**
